# LangGraph Data Plane Production Configuration
# Optimized for 5000 concurrent users

config:
  # LangSmith configuration
  langsmithApiKey: "" # Your LangSmith API Key
  langsmithWorkspaceId: "" # Your Workspace ID
  hostBackendUrl: "https://api.host.langchain.com"
  smithBackendUrl: "https://api.smith.langchain.com"

# Production scaling configuration
replicaCount: 10  # Start with 10 replicas for high availability

image:
  repository: langchain/langgraph-dataplane
  tag: "latest"
  pullPolicy: IfNotPresent

# Resource configuration for high-load scenarios
resources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "2"
    memory: "4Gi"

# Auto-scaling configuration
autoscaling:
  enabled: true
  minReplicas: 10
  maxReplicas: 50  # Scale up to 50 replicas for 5000 users
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Environment variables for production optimization
env:
  # Database configuration (custom PostgreSQL)
  POSTGRES_URI_CUSTOM: "postgres://langgraph:${POSTGRES_PASSWORD}@postgres-primary:5432/langgraph_production?sslmode=disable"
  
  # Redis configuration (custom Redis cluster)
  REDIS_URI_CUSTOM: "redis://redis-cluster:6379/0"
  
  # Performance tuning
  BG_JOB_ISOLATED_LOOPS: "True"  # Prevent blocking
  BG_JOB_TIMEOUT_SECS: "7200"   # 2 hour timeout for long analyses
  LANGGRAPH_POSTGRES_POOL_MAX_SIZE: "200"  # Connection pool per replica
  
  # LLM optimization
  LLM_PROVIDER: "openai"
  DEEP_THINK_MODEL: "gpt-4o"
  QUICK_THINK_MODEL: "gpt-4o-mini"
  MAX_DEBATE_ROUNDS: "1"
  ONLINE_TOOLS: "true"

# Service configuration
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: trading-agents.your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: trading-agents-tls
      hosts:
        - trading-agents.your-domain.com

# Health checks
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 5  # Always keep at least 5 replicas running

# Network policies for security
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx
    - from:
      - podSelector:
          matchLabels:
            app: monitoring

# Node affinity for performance
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-type
        operator: In
        values: ["compute-optimized"]

# Pod anti-affinity for resilience
podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 100
    podAffinityTerm:
      labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["langgraph-dataplane"]
      topologyKey: kubernetes.io/hostname 