[variables]
PYTHON_VERSION = "3.11"

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "python main.py"

[providers]
# Force nixpacks to not auto-detect
python = true 